CREATE TABLE notas_estudiantes (
    id SERIAL PRIMARY KEY,
    carnet VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    tareas DOUBLE PRECISION NOT NULL,
    p1 DOUBLE PRECISION NOT NULL,
    p2 DOUBLE PRECISION NOT NULL,
    p3 DOUBLE PRECISION NOT NULL,
    examen_final DOUBLE PRECISION NOT NULL,
    nota_exacta DOUBLE PRECISION NOT NULL,
    nota_final INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL
);
