function nota = calcular_nota(tareas, p1, p2, p3, examen_final)

    nota = ...
        tareas * 0.25 + ...
        p1 * 0.16 + ...
        p2 * 0.17 + ...
        p3 * 0.17 + ...
        examen_final * 0.25;

endfunction


