function guardar_postgresql( ...
    conn, carnet, nombre, ...
    tareas, p1, p2, p3, examen_final, ...
    nota_exacta, nota_final, estado)

    carnet_sql = strrep(carnet, "'", "''");
    nombre_sql = strrep(nombre, "'", "''");
    estado_sql = strrep(estado, "'", "''");

    consulta = sprintf( ...
        ["INSERT INTO notas_estudiantes " ...
         "(carnet,nombre,tareas,p1,p2,p3,examen_final," ...
         "nota_exacta,nota_final,estado) " ...
         "VALUES ('%s','%s',%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%d,'%s');"], ...
        carnet_sql, nombre_sql, ...
        tareas, p1, p2, p3, examen_final, ...
        nota_exacta, nota_final, estado_sql);

    pq_exec_params(conn, consulta);

endfunction

