function guardar_txt( ...
    archivo_txt, carnet, nombre, ...
    tareas, p1, p2, p3, examen_final, ...
    nota_exacta, nota_final, estado)

    archivo = fopen(archivo_txt, 'a');

    if archivo == -1
        error('No se pudo abrir notas.txt');
    endif

    fprintf(archivo, ...
        '%s|%s|%.2f|%.2f|%.2f|%.2f|%.2f|%.2f|%d|%s\n', ...
        carnet, nombre, ...
        tareas, p1, p2, p3, examen_final, ...
        nota_exacta, nota_final, estado);

    fclose(archivo);

endfunction

